# Generated by Django 2.2.24 on 2021-10-16 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_keyresults_objectives'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyresults',
            name='objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keyresults_objective', to='home.Objectives'),
        ),
    ]
